// Code generated by log-gen. DO NOT EDIT.
package models

type Pic struct {
	Id     int64  `json:"id"`//
	OpenId string `json:"open_id"`//
	Url    string `json:"url"`//
	Ctime  int64    `json:"ctime"`//
	Sha    string `json:"sha"`//
	Size   int    `json:"size"`//
	Ip     string `json:"ip"`//
	Ua     string `json:"ua"`//
}

func (t *Pic) Pk() string {
	return "id"
}
func (t *Pic) TableName() string {
	return "t_pic"
}
