// Code generated by log-gen. DO NOT EDIT.
package models

type Url struct {
	Id     int64  `json:"id"`//
	Url    string `json:"url"`//'原始地址',
	Ctime  int64    `json:"ctime"`//
	OpenId string `json:"open_id"`//'用户ID',
	MsgId  int64  `json:"msg_id"`//'消息id',
	Sha    string `json:"sha"`//'md5',
	Size   int    `json:"size"`//'地址长度',
}

func (t *Url) Pk() string {
	return "id"
}
func (t *Url) TableName() string {
	return "t_url"
}
