// Code generated by log-gen. DO NOT EDIT.
package log

import "go.uber.org/zap/zapcore"

func Sugar() *SugaredLogger {
	return logger.Sugar()
}
func Named(s string) *Logger {
	return logger.Named(s)
}
func WithOptions(opts ...Option) *Logger {
	return logger.WithOptions(opts...)
}
func With(fields ...Field) *Logger {
	return logger.With(fields...)
}
func Level() zapcore.Level {
	return logger.Level()
}
func Check(lvl zapcore.Level, msg string) *zapcore.CheckedEntry {
	return logger.Check(lvl, msg)
}
func Log(lvl zapcore.Level, msg string, fields ...Field) {
	logger.Log(lvl, msg, fields...)
}
func Debug(msg string, fields ...Field) {
	logger.Debug(msg, fields...)
}
func Info(msg string, fields ...Field) {
	logger.Info(msg, fields...)
}
func Warn(msg string, fields ...Field) {
	logger.Warn(msg, fields...)
}
func Error(msg string, fields ...Field) {
	logger.Error(msg, fields...)
}
func DPanic(msg string, fields ...Field) {
	logger.DPanic(msg, fields...)
}
func Panic(msg string, fields ...Field) {
	logger.Panic(msg, fields...)
}
func Fatal(msg string, fields ...Field) {
	logger.Fatal(msg, fields...)
}
func Sync() error {
	return logger.Sync()
}
func Core() zapcore.Core {
	return logger.Core()
}
// End
